services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: pgdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=smartpoll_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  qr-access-app:
    container_name: qr-access-app
    build:
      context: ./qr-access-app
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - db
volumes:
  pgdata:
